name: Release/Update dependent

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      RELEASE_VERSION: 2.1.0-b${{ github.run_number }}

    strategy:
      matrix:
        project: [mqtt-to-telegram, fritzbox-to-mqtt-gw, owserver-to-mqtt-gw, hue-to-mqtt-gw, cups-to-mqtt]

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: 8
          server-id: github
          settings-path: ${{ github.workspace }}

      - name: Configure Git
        run: |
          git config --global user.email "2f.mail@gmx.de"
          git config --global user.name "MQTT Gateway Release Bot"

      - uses: fusion-engineering/setup-git-credentials@v2
        with:
          credentials: https://${{secrets.GIT_USERNAME}}:${{secrets.GIT_TOKEN}}@github.com/

      - name: Update version for ${{ matrix.project }}
        run: .github/workflows/update-versions.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
          PROJECTS: ${{ matrix.project }}
