name: Release/Update dependent

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      RELEASE_VERSION: 2.1.0-b${{ github.run_number }}

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: 8
          server-id: github
          settings-path: ${{ github.workspace }}

      - name: Configure Git
        run: |
          git config --global user.email "2f.mail@gmx.de"
          git config --global user.name "MQTT Gateway Release Bot"

      - name: Build with Maven
        run: .github/workflows/update-versions.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
